Check for existence of file command

diff --git a/scripts/lint-all b/scripts/lint-all
--- a/scripts/lint-all
+++ b/scripts/lint-all
@@ -3,6 +3,15 @@ set -e
 set -u
 set -o pipefail
 
+if ! [ -x "$(command -v file)" ]; then
+  echo "Error: file is not installed."  >&2
+  echo >&2
+  echo "The file command is required to enumerate all Python files in this repo." >&2
+  echo "On Debian/Ubuntu systems, run the following command to install it:" >&2
+  echo >&2
+  echo "  sudo apt-get install file" >&2
+  exit 1
+fi
 
 if [ -z "$@" ]; then
     echo "Usage: lint-all <command>"
